# Production stage
FROM golang:latest AS production

# Set the working directory to the app directory
WORKDIR /app

# Copy go.mod and go.sum files to the working directory
COPY go.mod go.sum ./

# Download and install Go module dependencies
RUN go mod download

# Copy the rest of the application code to the working directory
COPY . .

# Build the application
RUN go build -o app .

# Expose port 8080 for the application
EXPOSE 8080

# Start the application
CMD ["./app"]
