version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socium_rentalis
    ports:
      - 5678:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6666:6379

volumes:
  dbdata:
