version: "3.9"

services:      
  mysql:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socium_rentalis
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6666:6379

  mailhog:
    container_name: mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

volumes:
  dbdata:
