CREATE TYPE "user_types" AS ENUM (
  'admin',
  'partner',
  'user'
);

CREATE TYPE "gender" AS ENUM (
  'female',
  'male'
);

CREATE TABLE "city" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR UNIQUE,
  "telephone" varchar,
  "gender" gender,
  "password" varchar
);

CREATE TABLE "partner" (
  "partner_id" int PRIMARY KEY NOT NULL,
  "income" decimal
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booker_id" int NOT NULL,
  "partner_id" int NOT NULL,
  "schedule" TIMESTAMP DEFAULT (now()),
  "duration" time,
  "city_id" int NOT NULL,
  "category" int,
  "open" bool,
  "closed" bool,
  "completed" bool,
  "voided" bool
);

CREATE TABLE "invoice" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int NOT NULL,
  "booker_id" int NOT NULL,
  "open" bool,
  "closed" bool,
  "voided" bool
);

CREATE TABLE "review" (
  "booking_id" int PRIMARY KEY NOT NULL,
  "rating" int,
  "description" varchar
);

CREATE UNIQUE INDEX ON "city" ("id");

CREATE UNIQUE INDEX ON "category" ("id");

CREATE UNIQUE INDEX ON "user" ("id");

CREATE INDEX "by_city_id" ON "user" ("city_id");

CREATE UNIQUE INDEX ON "partner" ("partner_id");

CREATE UNIQUE INDEX ON "booking" ("id");

CREATE INDEX ON "booking" ("booker_id");

CREATE UNIQUE INDEX ON "invoice" ("id");

CREATE INDEX ON "invoice" ("booker_id");

CREATE UNIQUE INDEX ON "review" ("booking_id");

COMMENT ON COLUMN "review"."rating" IS 'range 1-5';

ALTER TABLE "user" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "partner" ADD FOREIGN KEY ("partner_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("booker_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("partner_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("category") REFERENCES "category" ("id");

ALTER TABLE "invoice" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");

ALTER TABLE "invoice" ADD FOREIGN KEY ("booker_id") REFERENCES "user" ("id");

ALTER TABLE "review" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");
