CREATE TYPE "user_types" AS ENUM (
  'admin',
  'partner',
  'user'
);

CREATE TYPE "gender" AS ENUM (
  'female',
  'male'
);

CREATE TABLE "city" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" string UNIQUE,
  "telephone" varchar,
  "gender" gender,
  "kota" int,
  "user_type" user_types
);

CREATE TABLE "partner" (
  "partner_id" int PRIMARY KEY NOT NULL,
  "rating" int,
  "income" decimal
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booker_id" int NOT NULL,
  "partner_id" int NOT NULL,
  "schedule" datatime DEFAULT (now()),
  "duration" time,
  "category" int,
  "open" bool,
  "closed" bool,
  "completed" bool,
  "voided" bool
);

CREATE TABLE "invoice" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int NOT NULL,
  "booker_id" int NOT NULL,
  "open" bool,
  "closed" bool,
  "voided" bool
);

CREATE TABLE "review" (
  "booking_id" int PRIMARY KEY NOT NULL,
  "rating" int,
  "description" varchar
);

COMMENT ON COLUMN "partner"."rating" IS 'rating 1-5';

COMMENT ON COLUMN "review"."rating" IS 'range 1-5';

ALTER TABLE "user" ADD FOREIGN KEY ("kota") REFERENCES "city" ("id");

ALTER TABLE "partner" ADD FOREIGN KEY ("partner_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("booker_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("partner_id") REFERENCES "user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("category") REFERENCES "category" ("id");

ALTER TABLE "invoice" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");

ALTER TABLE "invoice" ADD FOREIGN KEY ("booker_id") REFERENCES "user" ("id");

ALTER TABLE "review" ADD FOREIGN KEY ("booking_id") REFERENCES "booking" ("id");
